language: node_js
node_js:
  - '12'
services:
  - mysql
env:
  - NODE_ENV=test
before_install:
  - npm install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wapd_backend_test default character set
    utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - export JWT_SECRET=secret
before_script:
  - sequelize db:migrate --env test
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: W6XmOMoM6iEg0zWJQkNX3p9t4991a9o3GtHnWBG8QBZHCs1QraP7WvHIAmO004S8bvK4DSxtW+1Yv3vhLeoU4n7m0LGzOTGcgkG33mHLjp8HJyorf64VrpMU/17Wk9GJ8RRRxGQ0IoODO6zGzYTzPESaxzWr7DhlPQW0WWQpQsgatfM+3qBJnkTUg44FZybNoDNrBQRBU5Rr6Nq9gwWJ9SDqT6h2rsjDp2I+w3r30MfraxCZdogxJ4Zf3zeqNednAw2oMqfauE8SISc3RCFhtpF9G4oExt+23GxTuwlF+qlxVCINZayXXvLpPMFItU1DTwELaIo01KDsYJVdU/mfwc7f8NIx4p57zSuJCTk1pye9TNGM7/8PFTe1QdTl/vqa8Vm7K8R2mVhK8A6lwH1WkYP569RReLma6Ysvui1FUaoQPfor7G2Uaxcn9Cku+Hw0i4CmNkQnR4vvaWhcegDkwdEJhNyG1yyDGrjdCbHO/bJb/x6wCCgz+ZPiXH8I21+1bW7HRsV8hQXlMmKKGnmNDjUUAl52gDw1u10MsTxjUXcyDzgwUyH+3Ld/VNwwejEH6bMJl28K4eHzG2ffF35Mn21TH5dK6SzkYW5uhj31VEfFKz6i5gRHxqqzFGX3qRSPjDaK4y5J/8QEQXsv9Fkbs/RpuEQVaUq9BNC+p/EoiSA=
  app: t-wapd-backend
  on:
    repo: EasonLin0716/wapd-backend
